# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e20d237d92d46cf26b4514b3b0737f70b9aa8a57b5ef0b5a2b0819c7f30eba48b0559915386dffbfae201ff47a179b7a16f9d7f70c002ac75d57f9b12b2755

test:
  secret_key_base: e7941cc2434b45c254451cf72d33f7bf010282747092e51cb08c415f29ca24f3dae727de2b82eb25952f465d44c1a99e837f5ba84a62ef475ae035cddc913fc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
